# Generated by Django 3.0.6 on 2020-05-31 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='address',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=400),
        ),
    ]
