# Generated by Django 3.0.6 on 2020-05-29 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200529_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='service')),
            ],
            options={
                'verbose_name': 'My Service',
                'verbose_name_plural': 'My Services',
            },
        ),
    ]
