# Generated by Django 3.0.6 on 2020-05-29 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentWorks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='recent_works')),
            ],
            options={
                'verbose_name': 'Recent Work',
                'verbose_name_plural': 'Recent Works',
            },
        ),
    ]
