# Generated by Django 3.0.6 on 2020-05-29 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_recentworks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Add the title of your video...', max_length=400)),
                ('video', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
