# Generated by Django 3.0.6 on 2020-05-29 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='time',
        ),
    ]
