# Generated by Django 3.0.6 on 2020-05-29 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_hobby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobby',
            name='profile',
        ),
    ]
