# Generated by Django 3.0.6 on 2020-05-29 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_hobby_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherBusiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_description', models.CharField(max_length=1000)),
                ('long_description', models.TextField()),
                ('image', models.ImageField(upload_to='about')),
            ],
            options={
                'verbose_name': 'Other business',
                'verbose_name_plural': 'Other businesses',
            },
        ),
        migrations.AlterModelOptions(
            name='career',
            options={'verbose_name': 'My career', 'verbose_name_plural': 'My careers'},
        ),
    ]
